; PlatformIO Project Configuration File
[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32@^6.13.0       ; 最新稳定平台，自动匹配 ESP32 工具链
framework = espidf
board = esp32dev
board_build.partitions = partitions_example.csv
monitor_speed = 115200
monitor_filters = direct

; 如果需要显示 OLED，可以加定义开启
board_build.extra_flags =
    -D CONFIG_USE_OLED=1